[server]
enableXsrfProtection = true

[theme]
primaryColor = "#F39C12"
backgroundColor = "#F4F4F4"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#333333"
font = "sans serif"

[logger]
level = "info"

[client]
displayEnabled = true
