[server]
address = "0.0.0.0"
enableXsrfProtection = true

[theme]
primaryColor = "#F39C12"
backgroundColor = "#E5E5E5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#333333"
font = "sans serif"

[logger]
level = "info"

[client]
displayEnabled = true
